app:
  jwtSecret: JWTSecretKey
  jwtExpirationInMs: 604800000

spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true


  security:
    user:
      name: kata
      password: Kata@Password
server:
  port: 8081
debug: false
